version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./cookies:/app/cookies
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      - COOKIES_PATH=/app/cookies/instagram.com_cookies.txt
      # Chrome/browser settings for cookie extraction
      - CHROME_BIN=/usr/bin/chromium-browser
      - DISPLAY=:99
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    # Add security context for browser access
    security_opt:
      - seccomp:unconfined
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    # Health check
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    restart: unless-stopped
    # Persist Redis data
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    # Health check for Redis
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 3
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

volumes:
  redis_data:
